### PR TITLE
Docker local running

### PR DESCRIPTION
**Pull request by wolfy-j**
- make temporal server work

### CODE REVIEW

**Comment by wolfy-j** [comment]
Confirmed docker working on local setup. 

Working on the app container (I'll use a different image than you).

**Comment by wolfy-j** [comment]
Actually I would try to stick to Ubuntu, but we recommend using Alpine.

**Comment by wolfy-j** [comment]
This is a good example using official PHP images: https://github.com/n1215/roadrunner-docker-skeleton/tree/master/containers/roadrunner

**Comment by wolfy-j** [comment]
@mozey I simplified the app docker and it now launches correctly and connects to the temporal server. However, it lacks MySQL DB at the moment. I need to run for a few hours but it should be possible to create db from container bash and then run migrations.

**Comment by wolfy-j** [comment]
We also have to add `wait-for-it` in cases when app starts before the server.

**Comment by wolfy-j** [comment]
I think it would be easier to add another MySQL container for app DB. I hope you can pick up the DB portion, if not - I can try later this weekend.

**Comment by wolfy-j** [comment]
Ok, I've added a code to init DB and migrations for it. It should be working now.

You can access app in cli via:

```
$ docker-compose exec s2s-worker bash
$ cd /app
$ php app.php
```

**Comment by wolfy-j** [comment]
This docker is ready to be used, simply run `docker-compose build && docker-compose up`. No scripts should be required to kick off the app.

**Comment by flumonion** [comment]
Great, the docker setup worked!

However, I cannot start the orchestration. The other services seem fine.

```
bash-5.1 php app.php start
Queue supervisor: failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refuse
```

I also cannot push to the queue, but is this because the above failed?

```
bash-5.1# php app.php push bob "hello world" -s 10
 [Spiral\RoadRunner\Jobs\Exception\JobsException]                                                                                                                                                                
 Opis\Closure\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) 
in /app/vendor/spiral/roadrunner-jobs/src/Queue/Pipeline.php:96
```

**Comment by wolfy-j** [comment]
Going to take a look today.

**Comment by wolfy-j** [comment]
My bad, I forgot to update .env.sample with proper TEMPORAL_ADDRESS for app to connect. Please pull the updates.

**Comment by wolfy-j** [comment]
@flumonion

**Comment by flumonion** [comment]
That works! thanks.

**Comment by mozey** [comment]
@wolfy-j Thanks! All the changes make sense. There is just one thing that confuses me a bit, [these lines](https://github.com/stock2shop/queue-orchestration/blob/feature/docker-local/docker-compose.yml#L99) seems to be a duplicate of [this line](https://github.com/stock2shop/queue-orchestration/blob/feature/docker-local/Dockerfile#L54)?

**Comment by wolfy-j** [comment]
Well, in Docker file we run assuming that temporal and DB already exists and running (like at prod). But in docker-compose they could be empty so we need pre-init routine.

**Pull request merged**
