### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by mozey**
@flumonion not quite working yet, see [README.stock2shop.md](https://github.com/stock2shop/dynamic-queue-routing-on-temporal/blob/docker/README.stock2shop.md)

### CODE REVIEW

**Comment by mozey** [comment]
As per the file linked above, the temporal plugin is timing out trying to connect to port 7233, that is the [same port as the Dockerfile](https://github.com/stock2shop/dynamic-queue-routing-on-temporal/blob/docker/docker-compose.yml#L50). Possibly I need to change the connection string use the [service name](https://github.com/stock2shop/dynamic-queue-routing-on-temporal/blob/docker/docker-compose.yml#L99), instead of 127.0.0.1

Where do I change that?

**Comment by mozey** [comment]
@flumonion can't tag wolfy-j, can you add him to this repo?

**Comment by flumonion** [comment]
>@flumonion can't tag wolfy-j, can you add him to this repo?

done

**Comment by mozey** [comment]
@wolfy-j I'm getting the error below when I try to run the example in docker
```
error: temporal_plugin_serve: failed reaching server... Error while dialing dial tcp 127.0.0.1:7233
```

How do I configure the plugin to use the docker-compose service name instead, i.e. [temporal:7233](https://github.com/stock2shop/dynamic-queue-routing-on-temporal/blob/docker/docker-compose.yml#L59)?

**Comment by mozey** [comment]
@flumonion @wolfy-j I've merged the latest changes from [upstream](https://github.com/wolfy-j/queue-orchestration). 

For us to evaluate this code it has to be running in docker containers... 

Currently stuck on the error below when running `php app.php configure`
```
[Cycle\Database\Exception\StatementException]
SQLSTATE[HY000] [1049] Unknown database 'what_must_this_be'
in /mnt/app/vendor/cycle/database/src/Driver/MySQL/MySQLDriver.php:56
```

Also not sure where to configure the temporal plugin to connect to [temporal:7233](https://github.com/stock2shop/dynamic-queue-routing-on-temporal/blob/docker/docker-compose.yml#L59), I don't see a setting for this in `.env.sample`

Once I can get `./rr serve` to run in the "s2s-worker" container, I'll add the commands in **README.stock2shop.md** to the Dockerfile

**Comment by wolfy-j** [comment]
I just found this ticket, sorry! There a temporal and queue configuration on application server level, in `.rr.yaml`. The error you are getting on `configure` is about unknown database you use. When you running MySQL container you can specify the name for the app. DB is needed for counter syncs (otherwise you can replace it with anything else). I'll check the docker-compose tomorrow, I finally managed to fix Docker on Windows.

**Comment by mozey** [comment]
> temporal and queue configuration on application server level, in .rr.yaml

Ah! [ripgrep](https://github.com/BurntSushi/ripgrep) wasn't searching dotfiles by default...

Think I'm close now, I get this error when trying to run `./rr serve`
```
temporal_plugin_serve... lookup temporal on 127.0.0.11:53: no such host
```

What is that port used for? No result when I search the repo, e.g.
```
rg -. ":53"
```

**Comment by wolfy-j** [comment]
The default temporal port for server is `7233`. Not sure why telnet port is coming here.

**Comment by mozey** [comment]
Yes, I've set [temporal:7233](https://github.com/stock2shop/queue-orchestration/blob/docker/.rr.yaml#L22), and that seems to be resolving correctly.

53 is actually DNS (telnet is 23). Here is a [similar issue](https://github.com/temporalio/temporal/issues/2539)

**Comment by mozey** [comment]
Possibly something is not quite right with how I've setup the [docker networking](https://github.com/stock2shop/queue-orchestration/blob/docker/docker-compose.yml#L101)?

**Comment by mozey** [comment]
Inside the s2s-worker container, [these commands](https://github.com/stock2shop/queue-orchestration/blob/docker/docker-rr.sh#L3) work. So the `temporal*` service names do resolve on the docker network

**Comment by wolfy-j** [comment]
I can make it working tomorrow. What error are you getting now?

**Comment by mozey** [comment]
Still this one https://github.com/stock2shop/queue-orchestration/pull/1#issuecomment-1198011051

**Comment by wolfy-j** [comment]
Sounds like the temporal server can not start due to the missing dynamic config (for me locally). I would recommend making temporal work first. Doing some local tweaking at the moment.

**Pull request merged**
